#!/bin/bash

# SYNOPSIS
#     Compares a Mac app audit file with the local state and offers to sync missing apps.
# DESCRIPTION
#     Reads a JSON audit file generated by audit_apps.sh.
#     Checks which apps are missing locally.
#     Offers to:
#     - Install missing Homebrew Casks.
#     - Install missing Mac App Store apps (via mas).
#     - List missing Manual apps for user intervention.

# ============================================================================
# CONFIGURATION
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIT_FILE="${1}"
LOG_FILE="$SCRIPT_DIR/sync.log"

# ============================================================================
# FUNCTIONS
# ============================================================================

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $1" | tee -a "$LOG_FILE"
}

usage() {
    echo "Usage: $0 <path_to_audit_json>"
    exit 1
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

if [[ -z "$AUDIT_FILE" || ! -f "$AUDIT_FILE" ]]; then
    usage
fi

log "Starting Mac App Sync Comparison..."

# 1. Run local audit first to compare
LOCAL_AUDIT="/tmp/local_mac_apps_audit.json"
log "Generating temporary local audit..."
"$SCRIPT_DIR/audit_apps.sh" "$LOCAL_AUDIT" > /dev/null

# 2. Compare using Python for robust JSON handling
log "Comparing remote audit with local state..."

python3 <<EOF | tee -a "$LOG_FILE"
import json
import sys

def load_audit(path):
    with open(path, 'r') as f:
        return json.load(f)

remote = load_audit('$AUDIT_FILE')
local = load_audit('$LOCAL_AUDIT')

local_names = {a['name'].lower() for a in local}
local_bundle_ids = {a['bundle_id'] for a in local if a['bundle_id'] != 'Unknown'}

missing = []
for app in remote:
    name_match = app['name'].lower() in local_names
    bundle_match = app['bundle_id'] != 'Unknown' and app['bundle_id'] in local_bundle_ids
    
    if not name_match and not bundle_match:
        missing.append(app)

if not missing:
    print("\n✅ All applications from the audit are already installed locally.")
    sys.exit(0)

print(f"\nFound {len(missing)} missing applications:")

homebrew = [a for a in missing if a['source'] == 'Homebrew']
app_store = [a for a in missing if a['source'] == 'App Store']
manual = [a for a in missing if a['source'] == 'Manual']

if homebrew:
    print("\n📦 Homebrew Casks to install:")
    for a in homebrew:
        print(f"  - {a['name']} (brew install --cask {a['source_id']})")

if app_store:
    print("\n🍎 Mac App Store apps to install:")
    for a in app_store:
        print(f"  - {a['name']} (mas install {a['source_id']})")

if manual:
    print("\n🛠 Manual installations required:")
    for a in manual:
        print(f"  - {a['name']} (v{a['version']})")

# Export commands for the shell script to pick up
with open('/tmp/sync_commands.sh', 'w') as f:
    if homebrew:
        f.write("echo 'Installing Homebrew Casks...'\n")
        for a in homebrew:
            f.write(f"brew install --cask {a['source_id']}\n")
    if app_store:
        f.write("echo 'Installing App Store apps...'\n")
        for a in app_store:
            f.write(f"mas install {a['source_id']}\n")

EOF

if [ -f /tmp/sync_commands.sh ] && [ -s /tmp/sync_commands.sh ]; then
    echo ""
    read -p "Do you want to run the automated installations (Homebrew & App Store)? (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        bash /tmp/sync_commands.sh
    fi
    rm /tmp/sync_commands.sh
fi

log "Sync comparison complete."
